name: Publish from VPS

on:
  schedule:
    - cron: "*/10 * * * *"   # ogni 10 minuti
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  export:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Assicura che siano presenti psql e jq
      - name: Ensure system dependencies
        shell: bash
        run: |
          set -e
          if ! command -v psql >/dev/null 2>&1; then
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-client
          fi
          if ! command -v jq >/dev/null 2>&1; then
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y jq
          fi

      # Carica /etc/ai-telemetry.env e promuove le variabili nell'ambiente del job
      - name: Load local env (PGHOST/PGPORT/PGDATABASE/PGUSER/PGPASSWORD/PGSSLMODE)
        shell: bash
        run: |
          set -e
          if [ ! -f /etc/ai-telemetry.env ]; then
            echo "❌ /etc/ai-telemetry.env non trovato" >&2
            exit 1
          fi

          # Sorgo il file e verifico le variabili richieste
          set -a
          . /etc/ai-telemetry.env
          set +a

          for v in PGHOST PGPORT PGDATABASE PGUSER PGPASSWORD PGSSLMODE; do
            if [ -z "$(eval echo \$$v)" ]; then
              echo "❌ Variabile mancante: $v nel file /etc/ai-telemetry.env" >&2
              exit 1
            fi
          done

          # Nascondo la password nei log
          echo "::add-mask::${PGPASSWORD}"

          # Esporto per gli step successivi
          {
            echo "PGHOST=${PGHOST}"
            echo "PGPORT=${PGPORT}"
            echo "PGDATABASE=${PGDATABASE}"
            echo "PGUSER=${PGUSER}"
            echo "PGPASSWORD=${PGPASSWORD}"
            echo "PGSSLMODE=${PGSSLMODE}"
          } >> "$GITHUB_ENV"

          # (facoltativo) log non sensibili
          echo "ℹ️ Using host=$PGHOST db=$PGDATABASE user=$PGUSER"

      - name: Generate Supabase status
        shell: bash
        run: |
          node /opt/ai-telemetry/exporters/generate_supabase_status.js
          node /opt/ai-telemetry/tools/sanitize.js /opt/ai-telemetry/out/supabase_status.json
          mkdir -p supabase
          cp /opt/ai-telemetry/out/supabase_status.json supabase/status.json

      - name: Generate VPS status
        shell: bash
        run: |
          bash /opt/ai-telemetry/exporters/generate_vps_status.sh
          node /opt/ai-telemetry/tools/sanitize.js /opt/ai-telemetry/out/vps_status.json
          mkdir -p vps
          cp /opt/ai-telemetry/out/vps_status.json vps/status.json

      - name: Commit & push
        shell: bash
        run: |
          git config user.email "runner@ai-telemetry.local"
          git config user.name  "AI Telemetry Bot"
          git add supabase/status.json vps/status.json
          git commit -m "update(vps): $(date -u +%FT%TZ)" || echo "no changes to commit"
          git push
